export default {
  FORBIDDEN: "Forbidden",
  SESSION_TIME_OUT: "Session Time Out",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "Bad Request",
  LOGIN_FAIL: "Login Fail",
  NOT_FOUND: "Not Found",
  EVOUCHER_NOT_FOUND: 'e-voucher does not exist',
  LIMIT_REACH_VOUCER: "All e-voucher sold out",
  INVALID_PHONE_NO: "Invalid Phone Number",
  INVALID_USER_ID: "Invalid User id",
  LIMIT_REACH_GIFT: "Reached gift limit you can send",
  UNSUPPORTED_PAYMENT: "Unsupporeted payment for this e-voucher",
  LUNACTIVE_EVOUCHER: "Unactive e-voucher",
}